# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 200)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bopen = QtWidgets.QPushButton(self.centralwidget)
        self.bopen.setObjectName("bopen")
        self.verticalLayout.addWidget(self.bopen)
        self.bbuild_grids = QtWidgets.QPushButton(self.centralwidget)
        self.bbuild_grids.setObjectName("bbuild_grids")
        self.verticalLayout.addWidget(self.bbuild_grids)
        self.bdenoise = QtWidgets.QPushButton(self.centralwidget)
        self.bdenoise.setObjectName("bdenoise")
        self.verticalLayout.addWidget(self.bdenoise)
        self.bsave = QtWidgets.QPushButton(self.centralwidget)
        self.bsave.setObjectName("bsave")
        self.verticalLayout.addWidget(self.bsave)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bopen.setText(_translate("MainWindow", "打开文件"))
        self.bbuild_grids.setText(_translate("MainWindow", "划分格网"))
        self.bdenoise.setText(_translate("MainWindow", "统计滤波"))
        self.bsave.setText(_translate("MainWindow", "保存结果"))
