# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_windowView.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QStyle


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        icon = QApplication.style().standardIcon(QStyle.SP_DialogOpenButton)
        self.actionopen.setIcon(icon)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        icon = QApplication.style().standardIcon(QStyle.SP_DialogSaveButton)
        self.actionsave.setIcon(icon)
        self.actionsave.setObjectName("actionsave")
        self.actionbuild_grids = QtWidgets.QAction(MainWindow)
        icon = QApplication.style().standardIcon(QStyle.SP_FileDialogListView)
        self.actionbuild_grids.setIcon(icon)
        self.actionbuild_grids.setObjectName("actionbuild_grids")
        self.actiondenoise = QtWidgets.QAction(MainWindow)
        icon = QApplication.style().standardIcon(QStyle.SP_MediaPlay)
        self.actiondenoise.setIcon(icon)
        self.actiondenoise.setObjectName("actiondenoise")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu_2.addAction(self.actionbuild_grids)
        self.menu_2.addAction(self.actiondenoise)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionsave)
        self.toolBar.addAction(self.actionbuild_grids)
        self.toolBar.addAction(self.actiondenoise)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "计算"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopen.setText(_translate("MainWindow", "打开文件"))
        self.actionsave.setText(_translate("MainWindow", "保存结果"))
        self.actionbuild_grids.setText(_translate("MainWindow", "划分格网"))
        self.actiondenoise.setText(_translate("MainWindow", "统计滤波"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
