# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopenbl = QtWidgets.QAction(MainWindow)
        self.actionopenbl.setObjectName("actionopenbl")
        self.actionopencode = QtWidgets.QAction(MainWindow)
        self.actionopencode.setObjectName("actionopencode")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionencode = QtWidgets.QAction(MainWindow)
        self.actionencode.setObjectName("actionencode")
        self.actiondecode = QtWidgets.QAction(MainWindow)
        self.actiondecode.setObjectName("actiondecode")
        self.menu.addAction(self.actionopenbl)
        self.menu.addAction(self.actionopencode)
        self.menu.addAction(self.actionsave)
        self.menu_2.addAction(self.actionencode)
        self.menu_2.addAction(self.actiondecode)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.actionopenbl)
        self.toolBar.addAction(self.actionopencode)
        self.toolBar.addAction(self.actionencode)
        self.toolBar.addAction(self.actiondecode)
        self.toolBar.addAction(self.actionsave)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "计算"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopenbl.setText(_translate("MainWindow", "读取经纬度"))
        self.actionopencode.setText(_translate("MainWindow", "读取地图编号(新）"))
        self.actionsave.setText(_translate("MainWindow", "保存结果"))
        self.actionencode.setText(_translate("MainWindow", "计算地图编号"))
        self.actiondecode.setText(_translate("MainWindow", "计算图廓点经纬度"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
